cache: pip
matrix:
  fast_finish: true
  include:
  - name: Black
    env: RUN=black
    language: python
    python: 3.7
    os: linux
    dist: bionic
install:
- pip install pycodestyle
script:
- pycodestyle iabwrapper/__init__.py
after_failure:
- sleep 10;
- echo == End ==
deploy:
  skip_existing: true
  provider: pypi
  user: __token__
  password:
    secure: GS3/GZ6GhTGp2txHv8s5fHt279Rq6U8X7/6xdQPq/0kDwnbgiLlgknzc8B1bTKlcUR2jzhZbiDNP8OexJy7rUrYIU/p6+DMBxGKNB0IcGveLKqzj4OsZuN4zAcyLbcBO7MyP9B4LOKag8X80kK+Zrkw5VPjU0pfCzVr60LNqWEyOQmKXeOHcuFzX07si1mYmC7XGyAciBveJHh7kfp5ej3v5xvCH6NoVmrXIH8AmP6gYJFloy7jYp5H0zZuyTvaLtkmQ6jqmC+75yv31/Lpx2Dh2dMZgfLYsPbr70Q9KAMQ59hi1LxQ5pYsCLt33Ei61CsxEiBMqDRJoRLCOZ/X6A2wm27zRI9RfxZ/80isuXIQmfuNQe24o8puD5HQXAQyBCHvVMn6BDVQ6CgkFeqn1+/4hJOL4u9TYtyy8PlFWRLJn4k2tFPgnxBtjLXWR1uZ9gdX3Q+213z0T0vIyWLpTxYgbZ8DUIJG6VE+tFs8hROdTvZqHWvHycRHcOEq9ZrGTNmzG6n39vCdDAqtUrzLLa1e21B8Q99sg12pr2qOGHQqibQEyArhrYhB9hlqiQqJB3obAmTSq+9lZwO8gfwUwO8IllBt6uKFX3zeUsHJ37pvszpKJEAkzF7ZBH22/C4k8UUCzGDPUGOupoZqMM5E307Y8Cw5CYKhjmvuEX6q7IZk=
  distributions: sdist bdist_wheel
  on:
    tags: true
